### ISSUE TITLE
Console message is particularly annoying

### ISSUE THREAD

**Issue by chrislloyd** [christianvuerings/vscode-phabricator#8]
I periodically get this message:

![Screen Shot 2020-03-11 at 9 10 18 AM](https://user-images.githubusercontent.com/718/76438436-384cbd00-6378-11ea-99dd-675716a1293c.png)

It's annoying because:

1. It's trying to update a cache (which is optional IMHO)
2. It steals focus from my current editor
3. I'm always connected to the Phab instance so I'm not sure why it's coming up anyway.

Some ideas to fix it:

1. Can updating the cache just fail silently? Having an up-to-date cache of usernames isn't necessary for using the extension.
2. If it _absolutely_ still needs to exist, could it be implemented as one of those pop-over, dismiss-able toast things instead? Those still show up but don't steal editor focus.
3. I have a feeling that the extension is extremely parallel in fetching data from Phab. While this is great for latency, it means I often hit Phab rate limits. I suspect this could be the root cause of the error. I first noticed this when opening up a new VSCode window and trying to do some `arc` commands, I got "rate limit hit" exceptions. My guess that this extension was pegging Conduit at the same time.

Happy to submit a patch given your guidance on how to fix!

**Update:** An example of what I mean about "those pop-over" things:

![Screen Shot 2020-03-11 at 9 19 12 AM](https://user-images.githubusercontent.com/718/76439329-79919c80-6379-11ea-8c3b-c520f991bf6b.png)

**Comment by christianvuerings** [comment]
@chrislloyd The cache update gets all users / projects and current user information. It's a pretty heavy since it does need to make quite a lot of requests.

Main recommendation would be to remove `log.show();` on this line:
https://github.com/christianvuerings/vscode-phabricator/blob/b2e4ce8e739eb8ab999dbc66c3b2fe8041430f66/src/cache.ts#L20

That way it'll no longer change the focus and fail silently.
